/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "hsxoxkoczljdvvckxmzy"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzeG94a29jemxqZHZ2Y2t4bXp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE1NzI1NTksImV4cCI6MjA4NzE0ODU1OX0.MTDpFU_M6VdTuSHY-mDxURq5PYLYEtR-3XhS32oeMNs"